### ISSUE TITLE
[BUG] GitHub page rendered site layout problem on phone

### ISSUE THREAD

**Issue by ankush** [world-class/REPL#196]
Banner image could be made responsive to avoid waste of screen space. 

![Screenshot_20210421-220733.png](https://user-images.githubusercontent.com/9079960/115593866-accf8a80-a2f2-11eb-9bc7-04d77dda09ee.png)

**Comment by sglavoie** [comment]
I believe this was not the intended result. Thank you and good catch. :smile:

**Comment by sglavoie** [comment]
Adding to this, there will also be a need to drop the width occupied by the contributors' table. Screenshot showing how it will look once the banner image is fixed (varies slightly depending on the device):

![image](https://user-images.githubusercontent.com/32682903/115643514-8570c180-a2e2-11eb-8854-188d34b47b96.png)

* It should probably be responsive for devices as small as 320px of width;
* The docs at https://allcontributors.org/docs/en/cli/configuration will also be helpful;

So that means having slightly smaller avatars (to keep some margins around) and 3 columns instead of 4 I guess.

**Comment by kaushikpadmanaban** [comment]
We could make a carousel for the contributors, and display some information about them. But that is a project on its own, and is wildly beyond the possibilities provided by Jekyll and the allcontributors configuration.

**Comment by sglavoie** [comment]
I agree @kaushikpadmanaban. Let's not go too far into this... unless you want to :grin:.

---

FIXED: Closing since this issue was fixed in #198 :tada:
