### ISSUE TITLE
Having docs to cover the application process 

### ISSUE THREAD

**Issue by Xuan-Lim** [world-class/REPL#34]
Hey there, great doc by the way. I'm starting soon and I've realized that future students curious about the programme would probably benefit from having a documentation clearly outlining the various processes and procedures that people might go through. I'll happily write it and put in a pull request for it. 

Let me know if you'd want to integrate that into the readme repo.

**Comment by sglavoie** [comment]
Sure! This sounds like a fantastic idea! Clearly, this was initially done for students who were already enrolled in the programme, but I believe it's a great plan to make this more approachable for future students as well. If you decide to have a look into [the Discord server](https://discord.gg/Hyxse35) before getting in (if you haven't already been there), you will see that many conversations revolve around welcoming prospective students having questions about this degree, so making this kind of information publicly available with fewer steps to take could serve to greatly encourage more students to join, which should ultimately benefit us all.

Thank you for the initiative! Any pull request will gladly be merged :wink:. I'll be there if you need anything. Did you envision this as a separate PDF document or something more readily available written in Markdown directly in the repo? In either case, I think that would work well, although I think it could have more impact if it's written as part of the repo in plain text instead of having to figure out where that info will be located. GitHub ranks pretty high when searching on Google, so anything with plain text should be relatively easy to find that way for newcomers. In any case, I don't want to impose any specific format, but if you planned to share a separate document, I would certainly like to have access to the original text so it can be added to the repo and additionally I would link back to that external document too if needed.

Thanks again and whatever you need, you know where to find me (I don't visit Discord anymore, but GitHub and emails are totally fine)! Slack has been a wonderful resource to complement our learning so far and has been the home of very informative, helpful and interesting discussions. Once you have access over there, you will be able to go through existing channels ([see a list here](https://github.com/world-class/REPL/blob/master/slack/README.md#channels)) and hopefully find a bunch of useful stuff to jump-start your learning since all the level 4 modules have been taken by at least one cohort of students so far and there are extra resources there that can't really be shared elsewhere :+1:.

**Comment by Xuan-Lim** [comment]
Ha ha sweet, I'll get that written and I'll put a pull request in:). You've mentioned some great ideas I'll definitely make a postit somewhere to have this info in:)

I'm probably going to write the guide in markdown:) Probably going to create a file /before_uol or /applying_to_uol and write it as a readme.md (a version in PDF that is made available for download that's made from the .md could work too - but that might be for after I write the doc:P) 

Yeah I'll let you know if I need anything, thanks:)
