### ISSUE TITLE
Greetbot should be replaced with Slack workflow for onboarding

### ISSUE THREAD

**Issue by amenat** [world-class/REPL#95]
E.g. new users could be sent a form that will ask important details (like modules they registered for) and then send them customized info accordingly.

I'll do it after the exams. :stuck_out_tongue_winking_eye:

**Comment by sglavoie** [comment]
Great idea! I just checked and Slack workflow is indeed available for the `#general` channel too, so that's probably the best move to make. Considering that Greetbot will stop providing a decent free plan starting from June (because they send me spam on Slack to tell me that among other things, by the way), it makes sense to go for something that's already well integrated.

I think this could be of great benefit for other channels too, but starting with `#general` is definitely a superb idea! Thanks for pointing this out! We could also very simply adapt the text that is currently being sent by Greetbot too so it won't be a huge challenge to undertake:
https://github.com/world-class/REPL/tree/master/slack#greetbot

**Comment by amenat** [comment]
I've replaced GreetBot with Slack workflow and added feedback mechanism too for future improvements.
